In [124]:
import numpy as np

In [125]:
num = [[1,2,3],[4,5,6]]

In [126]:
num = np.array(num)

In [127]:
num

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
num.shape

(2, 3)

In [129]:
# zeros, ones, eye, diag, randint, rand, randn

In [130]:
arr = np.zeros(5)

In [131]:
arr

array([0., 0., 0., 0., 0.])

In [132]:
arr = np.ones(6)# it bring the array with the number one 

In [133]:
arr 

array([1., 1., 1., 1., 1., 1.])

In [134]:
arr = np.zeros((2,4)) # it bring the 2x4 matrix

In [135]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
arr = np.eye(3) # it bring the digonal 1 and other zero.

In [137]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
arr = np.eye(3,4) # first parmeter is three that is row and second is 4 which is coulmn

In [139]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [140]:
arr = np.diag([1,4,5,7]) # it take the list in parmeter , unmber of parmeter is the number of row and it bribg the in diagonal
arr

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [141]:
rand_arr = np.random.randint(1,11,3) # it take the three parmeter first one is the start and it include second parmeter is end 
#but it is not include and three one is cout of randow numbers you whant in array
rand_arr

array([8, 4, 7])

In [142]:
rand_arr = np.random.rand(4)
# It take's a argument or parmeter and it give us random number between the 0 and 1.
rand_arr

array([0.67365999, 0.39147935, 0.70210437, 0.96569764])

In [143]:
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.09050988, 0.05812514, 0.58801742],
       [0.75117376, 0.51131739, 0.92050119]])

In [144]:
r_arr = np.random.randn(3,4)
# it give the random number which center to the 0 the mean's it bring the neg- the pos+ number near by 0.
r_arr

array([[-0.06900945, -1.93337331, -0.59246606, -0.94429363],
       [ 1.30199442, -1.13053572,  1.65625513,  1.09856504],
       [ 0.23694457,  1.64714958, -0.00965841, -0.99243166]])

In [145]:
np.mean(r_arr) # it give us the mean value of array or list

0.02242837400171388

### Reshaping data

In [146]:
arr = np.random.randint(1,100,20)
arr = arr.reshape(4,5) # this funtion take two argument's and multiplcation of argument is equal to the no. of element in arr <row,col> 
arr
# It bring the random value in between the 1 to 100

array([[99,  8, 38, 15,  1],
       [97,  3, 38, 48, 63],
       [62, 15, 62, 82, 38],
       [95, 20, 59,  7, 91]])

In [147]:
arr.ndim # It's tell the array are 2D ,3D .... or what

2

In [148]:
arr.shape #it give us no. of element or dimension of array 

(4, 5)

In [149]:
# reshaping in 3d array
arr = arr.reshape(2,2,5)
arr

array([[[99,  8, 38, 15,  1],
        [97,  3, 38, 48, 63]],

       [[62, 15, 62, 82, 38],
        [95, 20, 59,  7, 91]]])

In [150]:
# use of -1 in array
a = np.arange(1,111)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110])

In [151]:
a = a.reshape(5,-1)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22],
       [ 23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
         36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88],
       [ 89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110]])

In [152]:
a.shape

(5, 22)

In [153]:
a.ndim

2

In [154]:
# same random no. in every time using the ##seed funtion
np.random.seed(123)
arr = np.random.randint(1,50,10)
arr

array([46,  3, 29, 35, 39, 18, 20, 43, 23, 34])

### Indexcing and slicing of array's

In [155]:
arr = np.random.randint(1,50,10)
arr

array([33, 48, 10, 33, 47, 33, 48, 26, 20, 15])

In [156]:
arr[1:9:3] 

array([48, 47, 26])

In [157]:
arr = arr.reshape(2,5)
arr

array([[33, 48, 10, 33, 47],
       [33, 48, 26, 20, 15]])

In [158]:
# we are take the element for the above array that is 25 and 24 by using the slicing 
arr[0][2]

10

In [159]:
arr[1][-2]

20

In [160]:
arr[1,3] # by using the single bracket

20

In [161]:
arr = np.arange(1,51)
arr = arr.reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [162]:
# In the above array we need the only suarray that is 
# [1,2,3]
#[11,12,13]
arr[:2,:2]

array([[ 1,  2],
       [11, 12]])

In [163]:
arr[:3,2:6]

array([[ 3,  4,  5,  6],
       [13, 14, 15, 16],
       [23, 24, 25, 26]])

### Conditional Selection

In [164]:
a = np.random.randint(1,100,20)
a = a.reshape(4,5)
a

array([[37, 97, 81, 69, 50],
       [56, 68,  3, 85, 40],
       [67, 85, 48, 62, 49],
       [ 8, 93, 53, 98, 86]])

In [165]:
# appling the condition 
chan = a<50
a[chan]

array([37,  3, 40, 48, 49,  8])

In [166]:
# even number in array
a[a%2 == 0]

array([50, 56, 68, 40, 48, 62,  8, 98, 86])

### Arthmatical opration perform in tow array's 

In [167]:
a = np.array([12,3,4,5,6])
b = np.array([2,4,6,78,9])

In [168]:
a*b # a+b, a-b, a/b, a%b.....

array([ 24,  12,  24, 390,  54])

In [169]:
arr = np.random.randint(1,100,9).reshape(3,3)
arr1 = np.random.randint(1,55,9).reshape(3,3)
arr

array([[95, 28, 35],
       [98, 77, 41],
       [ 4, 70, 65]])

In [170]:
arr1

array([[12, 35, 11],
       [23, 14, 19],
       [37, 16, 44]])

In [171]:
arr+arr1 # also we perform the various operations

array([[107,  63,  46],
       [121,  91,  60],
       [ 41,  86, 109]])

In [172]:
# matrix multiplicaltion 
arr.dot(arr1)

array([[3079, 4277, 3117],
       [4464, 5164, 4345],
       [4063, 2160, 4234]])

In [173]:
arr1 = np.array([3,7,4,9]).reshape(2,2)
arr2 = np.array([6,2,5,8]).reshape(2,2)

In [174]:
arr1.dot(arr2)

array([[53, 62],
       [69, 80]])

### Usefull funtion in numpy

In [175]:
# that is min(),max(),argmin(),argmax(), sin(),cos(),sqrt(),linspace(),exp()
arr = np.random.randint(1,21,20).reshape(5,4)
arr

array([[13,  7, 14, 20],
       [17,  7, 15,  8],
       [12,  8,  2, 12],
       [ 6, 19, 18, 13],
       [19, 18,  2, 20]])

In [176]:
arr.max() # np.max(arr)

20

In [177]:
arr.min() 

2

In [178]:
# it's also call this way
np.max(arr) # arr.max()

20

In [179]:
# for number of max or min value index
arr.argmax()

3

In [180]:
# funtion for square root
np.sqrt(arr)

array([[3.60555128, 2.64575131, 3.74165739, 4.47213595],
       [4.12310563, 2.64575131, 3.87298335, 2.82842712],
       [3.46410162, 2.82842712, 1.41421356, 3.46410162],
       [2.44948974, 4.35889894, 4.24264069, 3.60555128],
       [4.35889894, 4.24264069, 1.41421356, 4.47213595]])

In [181]:
np.sin(arr)
# it's bring us sin value of the no. same as cos()

array([[ 0.42016704,  0.6569866 ,  0.99060736,  0.91294525],
       [-0.96139749,  0.6569866 ,  0.65028784,  0.98935825],
       [-0.53657292,  0.98935825,  0.90929743, -0.53657292],
       [-0.2794155 ,  0.14987721, -0.75098725,  0.42016704],
       [ 0.14987721, -0.75098725,  0.90929743,  0.91294525]])

In [182]:
 np.cos(arr)

array([[ 0.90744678,  0.75390225,  0.13673722,  0.40808206],
       [-0.27516334,  0.75390225, -0.75968791, -0.14550003],
       [ 0.84385396, -0.14550003, -0.41614684,  0.84385396],
       [ 0.96017029,  0.98870462,  0.66031671,  0.90744678],
       [ 0.98870462,  0.66031671, -0.41614684,  0.40808206]])

In [183]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [184]:
# Boolen array 
bo = np.array([1,0,0,0,0,1,1,0,1,0,1],dtype='bool')
bo

array([ True, False, False, False, False,  True,  True, False,  True,
       False,  True])

### Numpy Axis

In [185]:
matrix = np.random.randint(1,100,20).reshape(4,5)
matrix

array([[45, 49, 57, 92, 50],
       [87,  4, 68, 12, 22],
       [90, 99,  4, 12,  4],
       [95,  7, 10, 88, 15]])

In [186]:
# let's find the minimum number of row
np.min(matrix, axis=1)

array([45,  4,  4,  7])

In [187]:
# let's find thee maximum number of col..
matrix.max(axis=0)

array([95, 99, 68, 92, 50])

In [188]:
# let's find the sum of first two digit 
np.cumsum(matrix)

array([ 45,  94, 151, 243, 293, 380, 384, 452, 464, 486, 576, 675, 679,
       691, 695, 790, 797, 807, 895, 910])

### Shuffle and unique

In [189]:
# shuffle funtion in array numpy it shuffle the element of array
np.random.shuffle(matrix)
matrix

array([[95,  7, 10, 88, 15],
       [45, 49, 57, 92, 50],
       [87,  4, 68, 12, 22],
       [90, 99,  4, 12,  4]])

In [190]:
# If we need the uniqe element of array then we use the unique() 
np.unique(matrix, return_index = True, return_counts = True)

(array([ 4,  7, 10, 12, 15, 22, 45, 49, 50, 57, 68, 87, 88, 90, 92, 95, 99]),
 array([11,  1,  2, 13,  4, 14,  5,  6,  9,  7, 12, 10,  3, 15,  8,  0, 16],
       dtype=int64),
 array([3, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [191]:
np.unique(matrix).size

17

In [192]:
# horizontal stacking and vertical stacking
arr1 = np.random.randint(1,50,9).reshape(3,3)
arr2 = np.random.randint(20,50,9).reshape(3,3)

In [193]:
arr1

array([[13, 28, 39],
       [18, 47, 11],
       [36, 36,  2]])

In [194]:
arr2

array([[35, 33, 36],
       [25, 28, 33],
       [42, 34, 35]])

### horizontal and vertical stacking

In [195]:
np.hstack((arr1, arr2)) # horizontal stackin

array([[13, 28, 39, 35, 33, 36],
       [18, 47, 11, 25, 28, 33],
       [36, 36,  2, 42, 34, 35]])

In [196]:
# Vertical stacking
np.vstack((arr1,arr2))

array([[13, 28, 39],
       [18, 47, 11],
       [36, 36,  2],
       [35, 33, 36],
       [25, 28, 33],
       [42, 34, 35]])

In [197]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [198]:
b = np.array([20])

In [199]:
np.append(a,np.array([20,40]))

array([ 1,  2,  3,  4,  5, 20, 40])